import type { NextPage } from "next";
import Head from 'next/head'
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/ContactMe";

const Home: NextPage =() => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen overflow-scroll z-0">
      <Head>
        <title>Tathagat's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
{/*header*/}
    <Header />
        {/*Hero*/}
        <section id="hero" className="snap-center">
        <Hero />
        </section>
        
    {/*About*/}
    <section className="snap-center">
      <About />
    </section>
    {/*Skills*/}
    <section id="skills" className="snap-start">
      <Skills />
    </section>
    {/*Projects*/}
    <section id="projects" className="snap-start">
      <Projects />
    </section>
    {/*Contact*/}
    <section>
      <Contact />

    </section>
    </div>
  )
}

export default Home;