import type { NextPage } from "next";
import Head from 'next/head'
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Link from "next/link";

const Home: NextPage =() => {
  return (
    <div className="bg-[rgb(0,0,0)] text-white h-screen overflow-scroll z-0">
      <Head>
        <title>Portfolio By Tathagat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

    <Header />
        
        <section id="hero" className="snap-center">
        <Hero />
        </section>
        
    {/*About*/}

    <section  id="about" className="snap-center">
      <About />
    </section>


    {/*Skills*/}


    <section id="skills" className="snap-start">
      <Skills />
    </section>

    {/*Projects*/}

    <section id="projects" className="snap-start">
      <Projects />
    </section>
    {/*Contact*/}

    <section id="contact">
      <Contact />
    </section>

    <Link href="#hero">
    <footer className="sticky bottom-5 w-full cursor-pointer ">
    <div className="flex flex-col items-center">
    <img className="hover:grayscale-0 max-h-6" src="https://cdn-icons-png.flaticon.com/128/1946/1946436.png" />
    </div>
    </footer>
    </Link>
 
    </div>
  )
}

export default Home;